apiVersion: v1
kind: DeploymentConfig
metadata:
  name: openshift-mta
spec:
  replicas: 1
  selector:
    name: openshift-mta
  template:
    metadata:
      labels:
        name: openshift-mta
    spec:
      containers:
      - env:
        - name: SENDMAIL_DEFINE_SMART_HOST
          value: RELAYHOST
        - name: SENDMAIL_SMART_HOST_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: smtp-secret-openshift-mta
        - name: SENDMAIL_SMART_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: smtp-secret-openshift-mta
        - name: SENDMAIL_DISABLE_SENDER_RDNS
          value: "true"
        - name: SENDMAIL_ACCESS
          value: Connect:10 RELAY
        - name: SENDMAIL_FORCE_TLS_VERIFY
          value: "true"
        - name: SENDMAIL_ROOT_ALIAS
          value: /dev/null
        image: jkroepke/openshift-mta
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: openshift-mta
        ports:
        - containerPort: 25
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 30m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - mountPath: /var/spool/mqueue/
          name: queue
      subdomain: openshift-mta
      volumes:
      - emptyDir: {}
        name: queue
  triggers:
  - type: ConfigChange